name: Deploy
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install Deno
        uses: denoland/setup-deno@main
        with:
          deno-version: 1.25.1

      - name: Build site
        run: deno run -A ./build.ts

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: tc-ultra
          entrypoint: "server.js"
          root: .ultra
          import-map: importMap.server.json